---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:${AWS::Region}:${AWS_ACCOUNT_ID}:generatedTemplate/${GENERATED_TEMPLATE_ID}"

Resources:
  CloudFrontDistribution:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::Distribution"
    DeletionPolicy: "Retain"
    Properties:
      DistributionConfig:
        Logging:
          IncludeCookies: false
          Bucket: ""          # optional: ${LOG_BUCKET}.s3.amazonaws.com
          Prefix: ""
        Comment: ""
        DefaultRootObject: "index.html"
        Origins:
          - ConnectionTimeout: 10
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            ConnectionAttempts: 3
            OriginCustomHeaders: []
            DomainName: !GetAtt [ S3BucketSite, RegionalDomainName ]
            OriginShield:
              Enabled: false
            S3OriginConfig:
              OriginReadTimeout: 30
              OriginAccessIdentity: ""
            OriginPath: ""
            Id: "${ORIGIN_ID}"
        ViewerCertificate:
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"
          CloudFrontDefaultCertificate: false
          AcmCertificateArn: "arn:aws:acm:${AWS::Region}:${AWS_ACCOUNT_ID}:certificate/${ACM_CERTIFICATE_ID}"
        PriceClass: "PriceClass_All"
        DefaultCacheBehavior:
          Compress: true
          FunctionAssociations: []
          LambdaFunctionAssociations: []
          TargetOriginId: "${ORIGIN_ID}"
          ViewerProtocolPolicy: "redirect-to-https"
          GrpcConfig:
            Enabled: false
          TrustedSigners: []
          FieldLevelEncryptionId: ""
          TrustedKeyGroups: []
          AllowedMethods: ["HEAD","GET"]
          CachedMethods: ["HEAD","GET"]
          SmoothStreaming: false
          CachePolicyId: !Ref CloudFrontCachePolicy
        Staging: false
        CustomErrorResponses: []
        ContinuousDeploymentPolicyId: ""
        OriginGroups:
          Quantity: 0
          Items: []
        Enabled: true
        Aliases:
          - "${PRIMARY_DOMAIN}"      # e.g., brob314.com
          - "www.${PRIMARY_DOMAIN}"
        IPV6Enabled: true
        WebACLId: ""
        HttpVersion: "http2"
        Restrictions:
          GeoRestriction:
            Locations: []
            RestrictionType: "none"
        CacheBehaviors: []

  S3BucketPolicySite:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Retain"
    Properties:
      Bucket: !Ref S3BucketSite
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Id: "PolicyForCloudFrontPrivateContent"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${SITE_BUCKET_NAME}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS_ACCOUNT_ID}:distribution/${CLOUDFRONT_DISTRIBUTION_ID}"

  Route53ResolverResolverRuleAssociation:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Route53Resolver::ResolverRuleAssociation"
    DeletionPolicy: "Retain"
    Properties:
      VPCId: !Ref EC2VPC
      ResolverRuleId: "rslvr-autodefined-rr-internet-resolver"
      Name: "System Rule Association"

  CloudFrontOriginRequestPolicyEU:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginRequestPolicy"
    DeletionPolicy: "Retain"
    Properties:
      OriginRequestPolicyConfig:
        QueryStringsConfig:
          QueryStringBehavior: "all"
        Comment: "Policy for Elemental MediaTailor Origin"
        HeadersConfig:
          HeaderBehavior: "whitelist"
          Headers:
            - "origin"
            - "access-control-request-headers"
            - "x-forwarded-for"
            - "access-control-request-method"
            - "user-agent"
        CookiesConfig:
          CookieBehavior: "none"
        Name: "Managed-Elemental-MediaTailor-PersonalizedManifests"

  CloudFrontOriginRequestPolicyFw:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginRequestPolicy"
    DeletionPolicy: "Retain"
    Properties:
      OriginRequestPolicyConfig:
        QueryStringsConfig:
          QueryStringBehavior: "none"
        Comment: "Policy to forward user-agent and referer headers to origin"
        HeadersConfig:
          HeaderBehavior: "whitelist"
          Headers: ["referer","user-agent"]
        CookiesConfig:
          CookieBehavior: "none"
        Name: "Managed-UserAgentRefererHeaders"

  CloudFrontOriginRequestPolicy:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginRequestPolicy"
    DeletionPolicy: "Retain"
    Properties:
      OriginRequestPolicyConfig:
        QueryStringsConfig:
          QueryStringBehavior: "all"
        Comment: "Policy to forward all parameters in viewer requests"
        HeadersConfig:
          HeaderBehavior: "allViewer"
        CookiesConfig:
          CookieBehavior: "all"
        Name: "Managed-AllViewer"

  CloudFrontCachePolicy:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::CachePolicy"
    DeletionPolicy: "Retain"
    Properties:
      CachePolicyConfig:
        Comment: "Policy with caching enabled. Supports Gzip and Brotli compression."
        MinTTL: 1
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          QueryStringsConfig:
            QueryStringBehavior: "none"
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: "none"
          CookiesConfig:
            CookieBehavior: "none"
          EnableAcceptEncodingGzip: true
        DefaultTTL: 86400
        Name: "Managed-CachingOptimized"

  Route53HostedZone:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Route53::HostedZone"
    DeletionPolicy: "Retain"
    Properties:
      VPCs: []
      HostedZoneConfig:
        Comment: "HostedZone created by Route53 Registrar"
      Name: !Sub "${PRIMARY_DOMAIN}."

  EC2VPC:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::VPC"
    DeletionPolicy: "Retain"
    Properties:
      CidrBlock: "172.31.0.0/16"
      EnableDnsSupport: true
      InstanceTenancy: "default"
      EnableDnsHostnames: true
      Tags: []

  CloudFrontOriginAccessControl:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginAccessControl"
    DeletionPolicy: "Retain"
    Properties:
      OriginAccessControlConfig:
        SigningBehavior: "always"
        Description: "Created by CloudFront"
        SigningProtocol: "sigv4"
        OriginAccessControlOriginType: "s3"
        Name: !Sub "oac-${SITE_BUCKET_NAME}-${OAC_SUFFIX}"

  CloudFrontOriginRequestPolicyDI:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginRequestPolicy"
    DeletionPolicy: "Retain"
    Properties:
      OriginRequestPolicyConfig:
        QueryStringsConfig:
          QueryStringBehavior: "none"
        Comment: "Policy for S3 origin with CORS"
        HeadersConfig:
          HeaderBehavior: "whitelist"
          Headers:
            - "origin"
            - "access-control-request-headers"
            - "access-control-request-method"
        CookiesConfig:
          CookieBehavior: "none"
        Name: "Managed-CORS-S3Origin"

  CloudFrontOriginRequestPolicyKq:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginRequestPolicy"
    DeletionPolicy: "Retain"
    Properties:
      OriginRequestPolicyConfig:
        QueryStringsConfig:
          QueryStringBehavior: "all"
        Comment: "Policy to forward all parameters in viewer requests except for the Host header"
        HeadersConfig:
          HeaderBehavior: "allExcept"
          Headers: ["host"]
        CookiesConfig:
          CookieBehavior: "all"
        Name: "Managed-AllViewerExceptHostHeader"

  CloudFrontOriginRequestPolicyBH:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginRequestPolicy"
    DeletionPolicy: "Retain"
    Properties:
      OriginRequestPolicyConfig:
        QueryStringsConfig:
          QueryStringBehavior: "none"
        Comment: "Policy for custom origin with CORS"
        HeadersConfig:
          HeaderBehavior: "whitelist"
          Headers: ["origin"]
        CookiesConfig:
          CookieBehavior: "none"
        Name: "Managed-CORS-CustomOrigin"

  S3BucketSite:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "${SITE_BUCKET_NAME}"     # e.g., brob314.com
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  CloudFrontOriginRequestPolicyHP:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginRequestPolicy"
    DeletionPolicy: "Retain"
    Properties:
      OriginRequestPolicyConfig:
        QueryStringsConfig:
          QueryStringBehavior: "all"
        Comment: "Policy to forward all parameters in viewer requests and all CloudFront headers as of June 2022"
        HeadersConfig:
          HeaderBehavior: "allViewerAndWhitelistCloudFront"
          Headers:
            - "CloudFront-Viewer-Time-Zone"
            - "CloudFront-Viewer-Address"
            - "CloudFront-Viewer-Country"
            - "CloudFront-Is-IOS-Viewer"
            - "CloudFront-Is-Tablet-Viewer"
            - "CloudFront-Forwarded-Proto"
            - "CloudFront-Viewer-Country-Name"
            - "CloudFront-Is-Mobile-Viewer"
            - "CloudFront-Is-SmartTV-Viewer"
            - "CloudFront-Viewer-Country-Region"
            - "CloudFront-Is-Android-Viewer"
            - "CloudFront-Viewer-Country-Region-Name"
            - "CloudFront-Viewer-City"
            - "CloudFront-Viewer-Latitude"
            - "CloudFront-Viewer-Longitude"
            - "CloudFront-Viewer-Http-Version"
            - "CloudFront-Viewer-Postal-Code"
            - "CloudFront-Viewer-ASN"
            - "CloudFront-Is-Desktop-Viewer"
            - "CloudFront-Viewer-Metro-Code"
            - "CloudFront-Viewer-TLS"
        CookiesConfig:
          CookieBehavior: "all"
        Name: "Managed-AllViewerAndCloudFrontHeaders-2022-06"
